-- ============================================================================
-- MHINA FOREX — Documents (course books/PDFs)
-- Adds a 'document' media type and a proper document reference on lessons,
-- replacing the plain-URL notes_url approach (which had no access control
-- or view-only enforcement) with the same gated pattern used for video.
-- Run after 01_schema.sql, 02_rls_policies.sql, 03_triggers.sql.
-- ============================================================================

alter type media_type add value if not exists 'document';

alter table lessons
  add column if not exists document_media_id uuid references media_assets(id);

-- Storage bucket for course documents (PDFs/books). Created private —
-- nothing is publicly readable; access only via short-lived signed URLs
-- generated by our server after checking the requester's course tier.
insert into storage.buckets (id, name, public)
values ('course-documents', 'course-documents', false)
on conflict (id) do nothing;
